name: "Add Papers"

on:
  workflow_dispatch:
  push:
    paths:
      - "**.txt"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14.x"

      - name: Install dependencies
        run: npm ci

      - name: Fetch paper details and add the papers to the system
        run: node ./scripts/addPapers.js

      - name: Commit changes to records.json and currentPapers.csv
        uses: EndBug/add-and-commit@v9
        with:
          message: "Add new papers"
