name: "Add Candidate Papers"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"
  workflow_run:
    workflows: ["Add Papers"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14.x"

      - name: Install dependencies
        run: npm ci

      - name: Fetch candidate papers
        run: node ./scripts/addCandidatePapers.js

      - name: Commit changes to candidatePapers.csv
        uses: EndBug/add-and-commit@v9
        with:
          message: "Add new candidate papers"
